Repository prgrms-web-devcourse/Team-PODO-ODEEGO-FE, pull requests merged in 2023-02, with the labels that each got.

#11 feat: 지도 화면 생성
  .env
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/map/kakak-map.tsx
  src/pages/maps/index.tsx
  tsconfig.json
Labels: feature

#15 Feature/search
  .env
  .gitignore
  package-lock.json
  package.json
  src/components/search/not-found.tsx
  src/components/search/search-input.tsx
  src/pages/api/search.ts
  src/pages/index.tsx
  src/pages/place/index.tsx
  src/pages/search/index.tsx
  src/recoil/searchState.ts
  src/types/search-props.ts
Labels: feature

#19 Feature/makePolyline
  src/components/map/kakak-map.tsx
  src/pages/maptest/index.tsx
Labels: feature

#21 Design/places list page
  public/cafe1.png
  public/cafe2.png
  public/cafe3.png
  src/components/places/data/dummy.ts
  src/components/places/main.tsx
  src/components/places/place.tsx
  src/pages/places/index.tsx
Labels: style

#22 Design/place header
  .idea/jsLinters/eslint.xml
  src/components/place/place-input.tsx
  src/components/place/place-list.tsx
  src/components/place/place-tab-list.tsx
  src/components/place/place-total-list.tsx
  src/components/search/search-input.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/place.ts
  src/pages/index.tsx
  src/pages/place/index.tsx
  src/pages/places/index.tsx
  src/recoil/search-state.ts
  src/recoil/token-recoil.ts
Labels: style

#23 Feature/midway result button
  .gitignore
  src/components/map/kakak-map.tsx
  src/components/map/midpoint-button.tsx
  src/constants/css.ts
  src/hooks/.empty
  src/hooks/use-map.tsx
  src/pages/map/index.tsx
  src/pages/maps/index.tsx
  src/styles/global.tsx
  src/types/.empty
  src/types/api/midpoint.ts
  src/utils/.empty
  src/utils/dummy-data.ts
Labels: feature

#20 Feature/home address form
  .env.local.example
  package-lock.json
  package.json
  src/components/home/address-form.tsx
  src/components/home/form-input.tsx
  src/components/home/home-header.tsx
  src/components/home/home-main.tsx
  src/components/search/search-input.tsx
  src/hooks/use-multiple-inputs.ts
  src/recoil/search-state.ts
  src/recoil/test-state.ts
Labels: feature

#32 Feature/register
  package-lock.json
  package.json
  src/components/home/address-form.tsx
  src/components/home/home-header.tsx
  src/components/place/data/dummy.ts
  src/components/place/main.tsx
  src/components/place/place-list.tsx
  src/components/place/place.tsx
  src/components/signup/signup-input.tsx
  src/components/signup/signup-search.tsx
  src/example/react-hook-form/components/form-input.tsx
  src/example/react-hook-form/login/signup-form.tsx
  src/example/react-hook-form/signup/page.tsx
  src/example/react-hook-form/signup/signup-form.tsx
  src/hooks/use-signup-search.tsx
  src/pages/api/search.ts
  src/pages/login/index.tsx
  src/pages/place/index.tsx
  src/pages/signup/index.tsx
  src/recoil/test-state.ts
  src/recoil/token-recoil.ts
  src/types/register-props.ts
  src/utils/check-signup.ts
Labels: style, feature
