Repository prgrms-web-devcourse/Team-PODO-ODEEGO-FE, pull requests merged in 2023-03, with the labels that each got.

#44 fix: http -> https로 수정, mixed-content 에러 해결"
  src/pages/api/search.ts
Labels: bug

#48 배포 확인용 PR입니다
  src/pages/index.tsx
Labels: chore

#49 배포 확인용입니다 2번째
  src/pages/index.tsx
Labels: chore

#51 Jaekwan ahn feature/search link2
  src/components/search/search-input.tsx
  src/components/search/searh-confrim.tsx
  src/pages/api/search.ts
  src/recoil/token-recoil.ts
  src/types/search-props.d.ts
Labels: feature

#60 Feature/signin
  .github/CODEOWNERS.md
  .idea/inspectionProfiles/Project_Default.xml
  next.config.js
  src/components/layout/header.tsx
  src/components/signup/signup-input.tsx
  src/components/signup/signup-search.tsx
  src/constants/routes.ts
  src/hooks/use-map.tsx
  src/hooks/use-signup-search.tsx
  src/hooks/use-timeout-fn.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/group.ts
  src/pages/api/kakao-login.ts
  src/pages/api/kakao-logout.ts
  src/pages/api/place.ts
  src/pages/index.tsx
  src/pages/kakao/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/recoil/test-state.ts
  src/recoil/token-recoil.ts
  src/types/register-props.d.ts
  src/utils/check-signup.ts
  src/utils/storage.ts
Labels: style, feature, refactor

#69 Fix/signin redirect
  src/pages/api/kakao-login.ts
  src/pages/kakao/index.tsx
  src/pages/signin/index.tsx
Labels: bug

#65 Refactor/home address api error
  src/axios/groups.ts
  src/axios/mid-point.ts
  src/axios/post-example.ts
  src/components/home/form-input.tsx
  src/components/home/index.tsx
  src/constants/index.ts
  src/constants/routes.ts
  src/hooks/index.ts
  src/hooks/use-multiple-inputs.ts
  src/pages/api/v1/groups/index.ts
  src/pages/api/v1/groups/post/index.ts
  src/pages/api/v1/mid-point/search/index.ts
  src/pages/index.tsx
  src/recoil/access-token-state.ts
  src/recoil/index.ts
  src/utils/error.ts
Labels: refactor

#75 Feature/home address remaining time
  src/axios/groups.ts
  src/axios/mid-point.ts
  src/components/home/index.tsx
  src/components/home/modal/login-modal.tsx
  src/components/home/modal/select-modal.tsx
  src/components/home/modal/valid-group.tsx
  src/hooks/use-multiple-inputs.ts
  src/pages/index.tsx
Labels: feature

#77 Feature/places link
  src/components/map/places-button.tsx
  src/pages/map/index.tsx
  src/utils/dummy-data.ts
Labels: feature

#71 fix/searchAPIChange
  src/axios/config/axios-instance.ts
  src/axios/send-start-point.ts
  src/components/search/search-input.tsx
  src/constants/custom-error.ts
  src/pages/api/search.ts
  src/pages/api/v1/groups/startpoint/host/index.ts
  src/pages/api/v1/groups/startpoint/nonhost/index.ts
  src/pages/group/[groupId].tsx
  src/recoil/token-recoil.ts
  src/types/startpoint-props.d.ts
Labels: refactor

#81 Refactor/router group
  src/axios/groups.ts
  src/pages/group/[groupId].tsx
  src/pages/index.tsx
  src/recoil/group-state.ts
  src/recoil/index.ts
Labels: refactor

#80 Refactor/map markers
  src/hooks/use-map.ts
  src/hooks/use-map.tsx
  src/hooks/use-modal.ts
  src/pages/map/index.tsx
  src/types/map.d.ts
Labels: bug, refactor

#84 Refactor/custom markers
  public/avatar.svg
  src/components/map/map-header.tsx
  src/components/map/map-markers.tsx
  src/components/map/midpoint-button.tsx
  src/components/map/places-button.tsx
  src/constants/css.ts
  src/hooks/use-map.ts
  src/pages/api/v1/groups/index.ts
  src/pages/map/index.tsx
  src/recoil/midpoint-state.ts
  src/types/api/midpoint.d.ts
  src/types/map.d.ts
Labels: feature, refactor

#93 Refactor/search input + API Token Add
  src/axios/send-start-point.ts
  src/components/search/enter-searchpage-modal.tsx
  src/components/search/login-modal.tsx
  src/components/search/search-input.tsx
  src/components/search/searh-confrim.tsx
  src/components/search/set-startpoint-modal.tsx
  src/constants/custom-error.ts
  src/hooks/use-debounce.ts
  src/pages/api/v1/groups/startpoint/host/index.ts
  src/pages/api/v1/groups/startpoint/nonhost/index.ts
  src/recoil/token-recoil.ts
Labels: feature, refactor

#76 refactor/getSubway
  src/axios/get-subway.ts
  src/components/search/search-input.tsx
  src/pages/api/v1/subway/index.ts
Labels: refactor

#82 Refactor/signin
  .gitignore
  .idea/.gitignore
  .idea/dev_front.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/axios/instance.ts
  src/axios/mid-point.ts
  src/components/layout/header.tsx
  src/components/signup/signup-search.tsx
  src/hooks/use-signup-search.tsx
  src/pages/api/auth/login.ts
  src/pages/api/kakao-login.ts
  src/pages/api/kakao-logout.ts
  src/pages/api/odeego-leave.ts
  src/pages/kakao/index.tsx
  src/pages/signin/index.tsx
  src/utils/check-login.ts
  src/utils/check-signup.ts
  src/utils/createEmotionCahche.ts
  src/utils/storage.ts
Labels: style, feature, refactor

#95 Refactor/use token api
  src/axios/groups.ts
  src/axios/send-start-point.ts
  src/components/search/search-input.tsx
  src/hooks/use-localStorage.ts
  src/pages/api/v1/groups/[groupId]/index.ts
  src/pages/api/v1/groups/delete/index.ts
  src/pages/api/v1/groups/index.ts
  src/pages/api/v1/groups/post/index.ts
  src/pages/api/v1/groups/startpoint/host/index.ts
  src/pages/api/v1/groups/startpoint/nonhost/index.ts
  src/pages/group/[groupId].tsx
  src/pages/index.tsx
  src/pages/kakao/index.tsx
  src/recoil/token-recoil.ts
  src/types/api/group.d.ts
  src/utils/storage.ts
Labels: feature, refactor

#96 hotfix: 로그인 페이지 핫픽스
  src/pages/kakao/index.tsx
Labels: bug

#98 bugfix/remove useLocalStorage
  package.json
  src/axios/send-start-point.ts
  src/components/search/search-input.tsx
  src/hooks/use-localStorage.ts
  src/pages/group/[groupId].tsx
  src/pages/index.tsx
Labels: bug

#97 Fix/login page rediraction
  src/components/search/search-input.tsx
Labels: bug

#94 Refactor/api error code
  src/axios/groups.ts
  src/axios/mid-point.ts
  src/components/home/modal/valid-group.tsx
  src/pages/api/v1/groups/index.ts
  src/pages/api/v1/groups/post/index.ts
  src/pages/api/v1/mid-point/search/index.ts
  src/pages/group/[groupId].tsx
  src/pages/index.tsx
Labels: refactor

#90 Feature/place list api
  public/cafe1.png
  public/cafe2.png
  public/cafe3.png
  public/default-img01.jpg
  public/default-img02.jpg
  src/axios/place.ts
  src/components/place/data/dummy.ts
  src/components/place/main.tsx
  src/components/place/place-image.tsx
  src/components/place/place-input.tsx
  src/components/place/place-list.tsx
  src/components/place/place-tab-list.tsx
  src/components/place/place-total-list.tsx
  src/components/place/place.tsx
  src/hooks/index.ts
  src/hooks/use-intersection-observer.ts
  src/hooks/use-lazyload-image.ts
  src/pages/_document.tsx
  src/pages/api/v1/places/index.ts
  src/pages/place/index.tsx
  src/types/api/place.d.ts
Labels: feature

#100 Bugfix/fix routing
  src/components/map/map-header.tsx
  src/pages/group/[groupId].tsx
  src/recoil/search-state.ts
Labels: bug

#108 Fix/mid point duplicate start point
  src/pages/index.tsx
  src/utils/error.ts
Labels: bug

#103 Refactor/image optimization
  package-lock.json
  package.json
  src/axios/place.ts
  src/components/place/index.ts
  src/components/place/place-image.tsx
  src/components/place/place-list.tsx
  src/components/place/place.tsx
  src/hooks/index.ts
  src/pages/api/place.ts
  src/pages/api/v1/places/index.ts
  src/pages/place/index.tsx
  src/types/api/place.d.ts
Labels: bug, feature, refactor

#112 Feature/check token
  src/axios/groups.ts
  src/components/common/form-input.tsx
  src/components/home/modal/select-modal.tsx
  src/components/home/modal/valid-group.tsx
  src/components/layout/layout.tsx
  src/constants/custom-error.ts
  src/pages/_app.tsx
  src/pages/api/v1/groups/[groupId]/index.ts
  src/pages/group/[groupId].tsx
  src/pages/index.tsx
  src/styles/global.tsx
  src/types/api/group.d.ts
  src/utils/format-time.ts
Labels: feature

#110 Fix/startpointsubmit
  src/axios/send-start-point.ts
  src/components/search/search-input.tsx
  src/pages/api/v1/groups/startpoint/host/index.ts
  src/pages/api/v1/groups/startpoint/nonhost/index.ts
Labels: feature

#116 bugfix: uncaught error
  src/components/search/search-input.tsx
Labels: bug

#117 (Fix,Refactor)/header,signin
  package-lock.json
  package.json
  src/components/layout/header.tsx
  src/components/signup/signup-search.tsx
  src/hooks/use-signup-search.tsx
  src/pages/api/auth/login.ts
  src/pages/api/search.ts
  src/pages/api/user.ts
  src/pages/kakao/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
Labels: bug, style, feature, refactor

#129 fix: 리다이랙션 500 에러 수정
  src/pages/kakao/index.tsx
Labels: bug

#124 Bugfix/hydration error
  src/components/map/places-button.tsx
  src/hooks/use-map.ts
  src/pages/_document.tsx
  src/pages/map/index.tsx
Labels: bug, refactor

#119 Feature/insert my start point
  src/axios/get-my-startpoint.ts
  src/axios/send-start-point.ts
  src/components/search/search-input.tsx
  src/constants/custom-error.ts
  src/pages/api/v1/groups/startpoint/host/index.ts
  src/pages/api/v1/groups/startpoint/nonhost/index.ts
  src/pages/api/v1/members/defaultStation/index.ts
Labels: feature

#131 fix/logo
  package-lock.json
  src/components/layout/header.tsx
Labels: bug, style

#137 Style/refactor app
  public/favicon.ico
  public/kakao_login.svg
  public/kakao_login_medium_wide.png
  src/components/common/form-input.tsx
  src/components/common/global-modal.tsx
  src/components/home/form-input.tsx
  src/components/home/home-button.tsx
  src/components/home/index.tsx
  src/components/layout/header.tsx
  src/components/layout/layout.tsx
  src/components/layout/main.tsx
  src/components/layout/sub-header.tsx
  src/components/search/enter-searchpage-modal.tsx
  src/components/search/login-modal.tsx
  src/components/search/not-found.tsx
  src/components/search/search-input.tsx
  src/components/search/set-startpoint-modal.tsx
  src/components/signup/signup-input.tsx
  src/components/signup/signup-search.tsx
  src/constants/css.ts
  src/pages/group/[groupId].tsx
  src/pages/index.tsx
  src/pages/kakao/index.tsx
  src/pages/map/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/pages/signin/index.tsx
  src/styles/theme.tsx
Labels: style, refactor

#142 Hotfix/image
  public/kakao_login_medium_wide.png
  src/pages/signin/index.tsx
Labels: bug

#136 Refactor/place list page - preview test
  src/axios/place.ts
  src/components/layout/header.tsx
  src/components/place/place-tab-list.tsx
  src/components/place/place.tsx
  src/pages/api/v1/groups/index.ts
  src/pages/api/v1/groups/post/index.ts
  src/pages/api/v1/mid-point/search/index.ts
  src/pages/index.tsx
  src/pages/place/index.tsx
  src/pages/signin/index.tsx
  src/types/api/place.d.ts
Labels: refactor

#144 Refactor/member not found
  src/axios/groups.ts
  src/components/layout/header.tsx
  src/pages/api/v1/groups/index.ts
  src/pages/signin/index.tsx
Labels: bug, refactor
